- hosts: all
  become: yes
  vars:
    pterodactyl_dir: /var/www/pterodactyl
    panel_url: https://github.com/pterodactyl/panel/releases/latest/download/panel.tar.gz

  tasks:
    - name: Remove all files and directories in {{ pterodactyl_dir }}
      file:
        path: "{{ pterodactyl_dir }}"
        state: absent

    - name: Create {{ pterodactyl_dir }} directory
      file:
        path: "{{ pterodactyl_dir }}"
        state: directory
        mode: '0755'

    - name: Download the Pterodactyl panel archive
      get_url:
        url: "{{ panel_url }}"
        dest: "{{ pterodactyl_dir }}/panel.tar.gz"
      register: download_result

    - name: Extract the Pterodactyl panel
      unarchive:
        src: "{{ pterodactyl_dir }}/panel.tar.gz"
        dest: "{{ pterodactyl_dir }}"
        remote_src: yes
      when: download_result.changed

    - name: Set permissions for storage and bootstrap/cache
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ pterodactyl_dir }}/storage"
        - "{{ pterodactyl_dir }}/bootstrap/cache"

    - name: Install composer dependencies
      command:
        cmd: COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader
        chdir: "{{ pterodactyl_dir }}"

    - name: Clear Laravel views and config cache
      shell: |
        php artisan view:clear
        php artisan config:clear
      args:
        chdir: "{{ pterodactyl_dir }}"

    - name: Set ownership to www-data
      file:
        path: "{{ pterodactyl_dir }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    - name: Restart Laravel queue
      command:
        cmd: php artisan queue:restart
        chdir: "{{ pterodactyl_dir }}"

    - name: Bring Laravel application up
      command:
        cmd: php artisan up
        chdir: "{{ pterodactyl_dir }}"
