- hosts: all
  become: yes
  tasks:
    - name: Remove all files and directories in /var/www/pterodactyl
      file:
        path: /var/www/pterodactyl
        state: absent

    - name: Create /var/www/pterodactyl directory
      file:
        path: /var/www/pterodactyl
        state: directory
        mode: '0755'

    - name: Download the Pterodactyl panel archive
      get_url:
        url: https://github.com/pterodactyl/panel/releases/latest/download/panel.tar.gz
        dest: /var/www/pterodactyl/panel.tar.gz
      register: download_result

    - name: Wait for panel.tar.gz to exist (only if just downloaded)
      wait_for:
        path: /var/www/pterodactyl/panel.tar.gz
        state: present
        timeout: 60
      when: download_result.changed

    - name: Extract the Pterodactyl panel
      unarchive:
        src: /var/www/pterodactyl/panel.tar.gz
        dest: /var/www/pterodactyl
        remote_src: yes
      when: download_result.changed

    - name: Set permissions for storage and bootstrap/cache
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /var/www/pterodactyl/storage
        - /var/www/pterodactyl/bootstrap/cache

    - name: Install composer dependencies
      command:
        cmd: COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader
        chdir: /var/www/pterodactyl

    - name: Clear Laravel views and config cache
      shell: |
        php artisan view:clear
        php artisan config:clear
      args:
        chdir: /var/www/pterodactyl

    - name: Set ownership to www-data
      file:
        path: /var/www/pterodactyl
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    - name: Restart Laravel queue
      command:
        cmd: php artisan queue:restart
        chdir: /var/www/pterodactyl

    - name: Bring Laravel application up
      command:
        cmd: php artisan up
        chdir: /var/www/pterodactyl